# ⾃定义当前执⾏⽂件的名称
name: GitHub Actions with gitbook
# 整个流程在master分⽀发⽣push事件时触发
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # 运⾏在ubuntu-latest环境的虚拟机中
    steps:
    # 获取仓库源码
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    # 构建和部署
    - name: Install and Build
      # 由于⽰例项⽬代码并⾮在根⽬录,所以要这⾥⼿动进⼊了项⽬⽬录
      # 如果你代码本⾝就处于根⽬录则不需要再⼿动进⼊了
      run: |
        npm install
        npm install -D graceful-fs@2
        npm run build -- install
        npm run build -- build
        npm run test
    # 发布
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      # 环境变量
      with:
        ACCESS_TOKEN: ${{ secrets.ACC_TOKEN }} # GitHub 密钥 ACCESS_TOKEN 是在第⼆步Settings的Secrets中新增时定义的Name,要保持⼀致
        # 发布到指定分⽀
        BRANCH: gh-pages
        # 构建成果所在⽬录,默认位置都是在根目录
        FOLDER: ./_book
